ProtonMail/gluon

- internal/backend/mailbox.go
- internal/backend/state.go
- internal/backend/user_state.go
This patch adds `State.cleanupConnMetadata()` to cleanup the metadata
rather than relying on `State.close()`. If present in the letter the
state is also cleaned up when the SELECT or EXAMINE commands are
executed, which is not what we want.
> fix: Do not delete ConnMetadata store with SELECT or EXAMINE

- connector/dummy_simulate.go
- demo/demo.go
- imap/update_message_deleted.go
- internal/backend/backend.go
- internal/backend/ent/message.go
- internal/backend/ent/message/message.go
- internal/backend/ent/message/where.go
- internal/backend/ent/message_create.go
- internal/backend/ent/message_update.go
- internal/backend/ent/migrate/schema.go
- internal/backend/ent/mutation.go
- internal/backend/ent/runtime.go
- internal/backend/ent/schema/message.go
- internal/backend/message_tx.go
- internal/backend/state.go
- internal/backend/user.go
- internal/backend/user_state.go
- internal/backend/user_updates.go
- server.go
- store/disk.go
- store/memory.go
- store/store.go
- tests/db_utils.go
- tests/deletion_pool_test.go
- tests/event_waiter.go
- tests/server_test.go
- tests/session_test.go
This patch ensures that messages that have been marked as deleted by the
connector are evicted from the store and the user database. To do this,
the messages table has new field named `Deleted` which tracks whether
the connector has deleted this message.
On user creation we erase all messages from the database and the store
that are marked as such. On client logout we attempt to delete all
marked messages that are not in use by other sessions which share the
same user.
Finally this patch extends the store interface with `Delete()` and the
respective implementations for the on disk and memory storage.
> fix(GODT-1597): Handle permanently deleted messages

- go.mod
- internal/backend/user_updates.go
- internal/remote/operation.go
- internal/remote/operation_mailbox_delete.go
- internal/remote/operation_mailbox_update.go
- internal/remote/operation_message_add.go
- internal/remote/operation_message_create.go
- internal/remote/operation_message_flagged.go
- internal/remote/operation_message_remove.go
- internal/remote/operation_message_seen.go
- internal/remote/operation_temp_id.go
- internal/remote/user.go
- internal/remote/user_execute.go
- internal/remote/user_queue.go
Currently it is possible to have temporary IDs for mailboxes and
messages to become stale. It is possible, due to concurrency, that a
session pushes an operation which still uses a temporary ID that is no
longer valid.
Rather than locking the entire queue and updating all the remaining
entries, we now maintain two separate translation tables which are
evicted via separate operations.
This reduces the amount of time the queue spends in a locking state and
also guarantees that by the time the removal of the temporary ID is
processed by the operation queue no other operations exist that still
refer to this temporary ID.
> fix(GODT-1621): Fix race condition with temporary IDs

- internal/backend/backend.go
- internal/backend/user.go
- internal/remote/manager.go
- internal/remote/user.go
- internal/session/command.go
- internal/session/handle.go
- internal/session/handle_idle.go
- internal/session/session.go
- server.go
Annotate certain important goroutines so they can easily be located
in the debugger for problem analysis.
> chore: Add pprof annotations to important goroutines

- internal/backend/snapshot.go
- internal/backend/state.go
- tests/benchmark_big_mailbox_test.go
- tests/session_test.go
The previous pagination fix was not the most optimal possible. After
consulting with a database expert, if we sort the results by the row ID
and use a clause where the row ID is greater to the offset we are
currently evaluating, we can get better DB performance.
This patch also adds more tests to find other potential locations which
may trigger this error.
Finally we also fixed the error present in the listing of mailboxes.
> test(GODT-1615): Add more tests to trigger SQL error & Improve fix

- internal/backend/mailbox_fetch.go
- rfc822/parser.go
- tests/fetch_body_test.go
Fix crash that occurred by attempting to access children parts that were
not present. Issue was discovered through Dovecot's IMAP tests. A new
unit test was added to check for this as well.
> fix: Don't split Body into parts if there are none

- internal/session/handle_append.go
- internal/session/handle_login.go
- internal/session/handle_select.go
Add missing message text to responses reported by Gluon to satisfy IMAP
spec.
> fix(GODT-1715): Fix more IMAP tests reports

- rfc822/header.go
- rfc822/header_test.go
- tests/fetch_body_test.go
Fix the header parsing of fields that do not have a space after the
colon.
> fix(GODT-1729): Fix header parsing of fields without space

- connector/dummy.go
- connector/dummy_state.go
- connector/mock_connector/connector.go
- internal/backend/ent/migrate/schema.go
- internal/backend/ent/schema/mailbox.go
- store/mock_store/store.go
Currently in the Dummy connector, we create a new default INBOX mailbox
on every `Sync`. While this works fine for short lived tests, it causes
issues for cases where we need to run the same state multiple times. In
these cases certain queries fail as the name of the INBOX is not unique.
We have hard coded the value of the INBOX mailbox to a `0` in order to
guarantee that it remains unique on every run.
Finally a constraint has been added to the database table to catch this
error in the future.
> Fix: Add uniqueness constraint to mailbox names

- benchmarks/gluon_bench/benchmarks/benchmark.go
- benchmarks/gluon_bench/benchmarks/mailbox_create.go
- benchmarks/gluon_bench/main.go
- benchmarks/gluon_bench/server/local.go
- benchmarks/gluon_bench/server/remote.go
- benchmarks/gluon_bench/server/server.go
This patch introduces the `benchmark.Benchmark` interface to enable
benchmark to setup and tear down before actually running their checks.
For instance, this will be used by fetch to determine the number of
messages present in the mailbox.
This patch also introduces the `server.Server` interface to enable the
benchmark to be run against an external server. Current implementations
include a local implementation (run in process) and remote server which
the benchmark doesn't start, but can still connect to.
> feat(GODT-1917): Bechmark interface and server interface.

- benchmarks/gluon_bench/flags/general.go
- benchmarks/gluon_bench/gluon_benchmarks/sync.go
- benchmarks/gluon_bench/imap_benchmarks/client.go
- benchmarks/gluon_bench/imap_benchmarks/server/local.go
- benchmarks/gluon_bench/main.go
- benchmarks/gluon_bench/utils/connector_factory.go
- benchmarks/gluon_bench/utils/constants.go
- connector/dummy.go
Add a benchmark which checks the sync time for a new user with existing
messages.
The code has also been refactored to allow the use of different
connector implementation types. New connectors should be registered with
`utils.RegisterConnector()` before benchmark execution.
Existing IMAP benchmarks can now also run against different connector
implementations.
`ClearUpdates()` was added to the Dummy connector in order to clear the
update queue when benchmarking sync operations.
> feat(GODT-1917): Sync benchmark

- tests/sequence_range_test.go
The * refers to the last message in a mailbox. When the mailbox is
empty, we copy dovecot's behaviour, which is to return treat this as an
error with normal commands but to resolve without error with UID
commands.
> test(GODT-1584): * should resolve without error with UID commands

- benchmarks/gluon_bench/gluon_benchmarks/sync.go
- benchmarks/gluon_bench/imap_benchmarks/server/local.go
- demo/demo.go
- internal/backend/backend.go
- option.go
- server.go
- store/disk.go
- store/memory.go
- store/store.go
- tests/server_test.go
Refactor Gluon Server so that it owns the data generate for each user.
The data store path can be configured with the `WithDataPath` option.
The `AddUser` function is now meant to be used to create new user which
has not been added before. `LoadUser` has been added load existing data
from disk.
`AddUser` and `LoadUser` have been simplified. Gluon internally controls
the database parameters and `Store` implementation. To override the
default disk storage implementation, use the `WithStoreBuilder` option.
The user's data path can be queried with `Server.GetUserDataPath()`.
> chore: Refactor Server so that it own's the user database

- internal/backend/match.go
- internal/backend/match_test.go
- internal/backend/state.go
- tests/list_test.go
RFC3501 states:
An empty ("" string) mailbox name argument is a special request to
return the hierarchy delimiter and the root name of the name given
in the reference. The value returned as the root MAY be the empty
string if the reference is non-rooted or is an empty string.
We didn't return the empty string for non-rooted references.
> fix(GODT-1618): properly handle empty LIST pattern

- benchmarks/gluon_bench/store_benchmarks/create.go
It was not using the same file size as the rest of the benchmarks.
> Fix: Correct store create benchmark

- store/badger.go
Setting the badger logger option after already setting the level
overwrites the changed level, so this commit just removes the unused
option. We will inherit the level of the logrus standard logger anyway.
> chore: Remove dead logging code

- benchmarks/gluon_bench/store_benchmarks/create.go
- benchmarks/gluon_bench/store_benchmarks/delete.go
- benchmarks/gluon_bench/store_benchmarks/get.go
- benchmarks/gluon_bench/store_benchmarks/utils.go
- internal/backend/db.go
- internal/backend/db_mailbox.go
- internal/backend/db_message.go
- internal/backend/mailbox.go
- internal/backend/mailbox_fetch.go
- internal/backend/mailbox_fetcher.go
- internal/backend/mailbox_search.go
- internal/backend/match.go
- internal/backend/responders.go
- internal/backend/snapshot.go
- internal/backend/state.go
- internal/backend/state_actions.go
- internal/backend/user.go
- internal/backend/user_state.go
- internal/backend/user_updates.go
- internal/session/handle.go
- store/badger.go
- store/disk.go
- store/memory.go
- store/store_test.go
- tests/parallel_test.go
Ensure all the database queries are accessed through the scope of RWLock
to avoid the infamous "database locked" error and to allow more parallel
read only requests from clients.
The RWLock guarantees that only one goroutine/thread can write to the
datbase, therefore ensuring we never trigger the limitations of SQLite
DB which causes the error.
The removal of the global TX Lock now enables clients to perform more
read only request in parallel.
Going forward it is expected all database access to be accessed via the
`DB` type.
> Database RW Split

- connector/dummy.go
- internal/backend/backend.go
- internal/backend/user.go
- internal/remote/user.go
Rework goroutine shutdown so that we don't need to call
`Connector.Close()` when closing the backend user.
Two separate channels have been added ensure the blocking go-routines
exit when the Server shuts down or an user has been removed.
> fix(GODT-1647): Address double call to `Connector.Close()`

- internal/backend/context.go
- internal/backend/mailbox.go
- internal/backend/mailbox_fetch.go
- internal/backend/mailbox_search.go
- internal/backend/responders.go
- internal/backend/seqset.go
- internal/backend/snapshot.go
- internal/backend/snapshot_messages.go
- internal/backend/state.go
- internal/backend/state_actions.go
- internal/backend/state_filters.go
- internal/backend/state_updates.go
- internal/backend/user.go
- internal/backend/user_state.go
- internal/backend/user_updates.go
- internal/queue/ctqueue.go
- internal/queue/queued_channel.go
- internal/session/handle.go
- internal/session/handle_idle.go
- internal/session/session.go
- server.go
- tests/server_test.go
Prior to this patch the updates to other session states were applied
immediately by going through all the available states in `backend.user`
and applying the changes immediately.
This patch changes the architecture so that all state updates for other
session states are queued via a channel rather than executed
immediately. This removes the need for snapshot lock, snapshot messages
lock, IDLE lock and responder lock as we no longer have two sessions
accessing state from one another.
To ensure the current state is still update, we mark all context with
the stateID (when available) and if the stateID matches one of the
states in the list, the update is applied immediately.
The downside is that every state now has to verify that this update can
be executed locally rather than checking in …
> Remove state & snapshot locks

- internal/response/bye.go
- internal/session/handle.go
- internal/session/handle_delete.go
- internal/session/session.go
- internal/state/actions.go
- internal/state/state.go
- internal/state/updates.go
- tests/connection_test.go
- tests/delete_test.go
When a mailbox is deleted and selected, disconnect the client who issued
the deletion on success.
Other clients which also have this mailbox selected will be disconnected
through an update on their next command.
The above mimics the behavior of dovecot.
> fix(GODT-1842): Handle mailbox deletion with multiple clients

- internal/session/handle.go
- internal/session/handle_check.go
- internal/session/handle_close.go
- internal/session/handle_copy.go
- internal/session/handle_expunge.go
- internal/session/handle_fetch.go
- internal/session/handle_move.go
- internal/session/handle_search.go
- internal/session/handle_store.go
- internal/session/handle_uid.go
- internal/session/handle_unselect.go
- internal/state/mailbox_fetch.go
- internal/state/responders.go
- tests/deletion_pool_test.go
- tests/fetch_body_test.go
- tests/updates_test.go
This patch fixes the behavior of untagged responses to match dovecot.
All untagged responses are now sent at the end of the command before the
closing tag is sent and no longer before and after. Some of the unit
tests had to be updated to match this new behavior.
This patch also fixes fetch so that it applies the seen flag to the
snapshot on which fetch is operating. This is now possible as snapshots
aren't shared between sessions anymore.
> Untagged reponse behavior

- internal/backend/backend.go
- internal/backend/connector_updates.go
- internal/db/message.go
- internal/session/session.go
- internal/state/actions.go
- internal/state/mailbox.go
- internal/state/responders.go
- internal/state/snapshot.go
- internal/state/state.go
- internal/state/updates_mailbox.go
- internal/state/updates_remote.go
- tests/deletion_pool_test.go
- tests/draft_test.go
- tests/idle_test.go
- tests/recent_test.go
This patch removes the need for the snapshots to read new messages from the database when they arrive via an `exists` responder.
We have also updated the behavior of the `Recent` flag to match dovecot's implementation. If a client append a message to a selected mailbox only that client will receive the recent flags. If a client appends a message to a non-selected mailbox, the first state which receives the update will apply the recent flag.
To achieve the latter, we added a new update `ExistsStateUpdate` which enforces the logic described above in a thread safe manner.
> fix(GODT-1757): Recent flag behavior and snapshot db reads

- internal/state/mailbox.go
- internal/state/responders.go
- internal/state/state.go
Currently the only one responder needs to modify db state to clear the recent flags. By changing the interface to return an update object we can lock the db for writing on demand rather than all the time.
> refactor(GODT-1757): Reduce db locks for responders

- benchmarks/gluon_bench/imap_benchmarks/imap_benchmark_runner.go
Flags were being read before they were set.
> fix: Fix remote server operation for gluon_bench

- benchmarks/gluon_bench/imap_benchmarks/select.go
The append is currently slow because it takes a lot of time to load data from the mailbox. The select benchmark can be use to check this specific issue later once the append has been fixed.
> feat: Add Select benchmark

- internal/session/handle_append.go
- internal/session/responses.go
- internal/state/mailbox.go
- internal/state/snapshot.go
- internal/state/state.go
Do not load the entire mailbox from the database if it is not selected and only flush event if the mailbox is currently selected.
> fix(GODT-1570): Improve Append command perf

- benchmarks/gluon_bench/imap_benchmarks/server/local.go
- demo/demo.go
- server.go
- tests/server_test.go
When calling gluon.Serve(ctx, net.Listener), we take in a listener. We shouldn't close this when closing gluon as we don't own this listener. The surrounding caller who calls gluon.Serve(...) should be responsible for closing it, to avoid double-close errors.
> fix: Don't close the listener when closing the server

- internal/backend/connector_updates.go
- internal/db/message.go
- internal/state/responders.go
Batch incoming connector updates for new message to 1000 messages per transaction to avoid running into too many SQL variables.
We batched at outside of the transaction level so as not to completely block the other threads forever until we are done processing a high number of updates.
> fix(GODT-1570): Fix too many SQL Variable in sync benchmark

- benchmarks/gluon_bench/gluon_benchmarks/sync.go
- connector/connector.go
- connector/dummy.go
- connector/dummy_simulate.go
- connector/dummy_state.go
- imap/update_message_created.go
- internal/backend/connector_updates.go
- internal/backend/state_connector_impl.go
- internal/state/actions.go
- internal/state/connector.go
Update the `Connector.CreateMessage` to also require a parsed message type. This enabled the connector implementation to inspect the message without having to re-parse the message as we already do this before the connector request.
This patch separates the parsed message from the `MessageCreated` update so that we can use it in other locations in the code base.
> refactor(GODT-1570): Reuse parsed contents for messages

- imap/envelope_test.go
- imap/structure.go
- imap/update_message_created.go
- internal/state/mailbox_fetch.go
- rfc822/encrypt.go
- rfc822/header.go
- rfc822/header_test.go
- rfc822/parser.go
- tests/parsed_message_test.go
Applies the following improvements:
* Removed channel for parsing (unnecessary overhead)
* Improve merge multi-line and forLines - Do not use bytesReader and
BufferedReader (unnecessary overhead)
* Cache parsed header - avoids recalculation
These changes alone improve these parsed message benchmark code by
about 40% on average.
> improve header parsing code

- internal/backend/connector_updates.go
- internal/db/message.go
- tests/updates_test.go
The previous code did not properly handle message de-duplication code resulting in scenarios where duplicate message entries could be created.
> fix: Connector Message Create event handling

- internal/ids/header.go
- rfc822/encrypt.go
- rfc822/header.go
- rfc822/header_test.go
- rfc822/parser.go
To improve lookup after the header has been parsed all the entries are stored in a map.
Every single line of the header is stored as a linked list so we can perform order dependent queries or modify the header while preserving the original order. The result of mergedLine requests are cached to avoid this computation in the future.
The SetHeaderValue function has been updated so that it does not parse the full header, but rather sets the new value as the first value of the new header. This avoids having to parse the whole header to set our internal ID-Key
Finally our internal ID key was case-corrected according to the standard.
> refactor(GODT-1730): Refactor HeaderType

- go.mod
- go.sum
- tests/capability_test.go
- tests/connection_test.go
- tests/draft_test.go
- tests/login_test.go
- tests/search_test.go
- tests/select_test.go
- tests/sequence_range_test.go
- tests/session_test.go
- tests/testdata/dovecot-crlf
- tests/updates_test.go
* fix(godt-1599): make sure search before uses internal date.
* fix: more strict `testConnection.S` and `.Se` matching.
* fix(godt-1599): make sure search since/on uses internal date.
N.B. Dependency `emersion/go-mbox` was forked, added `GetMessageDelimiter` function and replaced in go.mod
> fix(GODT-1599): Make sure `search before/since/on` uses internal date.

- imap/structure_test.go
- imap/testdata/bounds.eml
- imap/testdata/rfc822.eml
- rfc822/header.go
- rfc822/header_parser.go
- rfc822/parser.go
The new header parser did not correctly deal with two edge cases:
1. The message contains an embedded RFC822 message with no header
2. Parsing something (not necessarily a header) with a key but no value
This fix checks that what we think is a header actually is one in a naive way by trying to parse it and seeing if it returns an error. It also handles the case that a header key was not finished being read by returning an error, indicating this wasn't a valid header).
> fix: Header parser (naive)

- imap/flags.go
- internal/backend/connector_updates.go
- internal/db/message.go
- internal/state/updates.go
Cost of retrieving deleted messages and filtering them and then updating the ones that were not set was about the same as just setting the value for every message in the list.
Return the flags as an array as there's no need to perform mapping operations.
> refactor(GODT-1570): Do less work with Flag modification

- internal/state/mailbox.go
- internal/state/snapshot.go
- internal/state/snapshot_messages.go
Speed up collection of all messages that need to be expunged by tracking this in their state rather than checking the flags.
> refactor(GODT-1570): Track expunge status on sanpshot messages

- imap/structure.go
- rfc822/mime.go
The standard library mime.ParseMediaType does not handle some edge cases. This commit exposes a package-level ParseMediaType function, allowing the standard library calls to be replaced with a custom function.
> feat: Expose ParseMediaType

- .github/workflows/pull-request.yml
- builder.go
- internal/contexts/context.go
- internal/state/mailbox_fetch.go
- internal/state/mailbox_search.go
- internal/state/responders.go
- internal/state/snapshot.go
- internal/state/snapshot_messages.go
- option.go
- server.go
- tests/append_test.go
- tests/server_test.go
Extendend snapshot with `appendMessageFromOtherState` to enable out of order UID insertion. Please check the comments in
`TestAppendCanHandleOutOfOrderUIDUpdates` for why this is necessary.
> fix(GODT-1760): Fix out of order UID panics

- connector/connector.go
- connector/dummy.go
- internal/backend/state_connector_impl.go
- internal/state/connector.go
- internal/state/state.go
- tests/list_test.go
- tests/lsub_test.go
- tests/session_test.go
Allow connector implementations to hide mailboxes from clients if necessary.
> feat(GODT-1742): Add `IsMailboxVisible` to `Connector`

- server_test.go
We drop items in the QueuedChannel on exit. This may include the last event. This causes the test to be flaky, so it has been removed because these events are not important at this stage.
> test: Delete flaky server_test.go

- internal/db/mailbox.go
It's possible for the context to be cancelled at any time. As such, we should not assume Save will succeed, and so should not use SaveX because it panics on failure.
> fix: Don't use SaveX when creating flags

- tests/list_test.go
INBOX is created by default in the dummy connector, no need to create it again.
> test: Remove extra INBOX creation call in test

- tests/main_test.go
- tests/server_test.go
By using a top-level test main, we can check for leaks that occur in the test fixture as well.
This commit also removes some old environment variables that are no longer used.
> test: Use a top-level test main for leak detection

- connector/connector.go
- connector/dummy.go
- connector/mock_connector/connector.go
- internal/backend/state_connector_impl.go
- internal/state/actions.go
- internal/state/connector.go
- internal/state/state.go
Remove `refresh` function as it is no longer required since we removed the operation queue. Additionally this function was causing a deadlock on error since the update it was waiting on could not be executed as the current operation has acquired the database lock.
> fix: Fix state connector deadlock

- internal/backend/connector_updates.go
- internal/db/mailbox.go
- tests/delete_test.go
- tests/deleted_test.go
- tests/session_test.go
- Ensure messages are removed from mailboxes if no state is selected.
- Ensure states are updated if the mailbox has been removed from remote.
> Fix connector update issues related to deletion of mailboxes and messages

- internal/backend/connector_updates.go
We set it above, so don't do it again when adding to the store.
> fix: Don't set the Internal ID in the header twice

- imap/update_message_created.go
- internal/backend/connector_updates.go
MessageCreated debug string has been improved and we now record the user id where the update is applied.
> refactor: Improve debug output for connector updates

- internal/backend/connector_updates.go
- internal/db/message.go
- tests/deleted_test.go
If the Connector sends a delete message update followed by a create message update we need to delete the existing message from the database on the spot so that it can be replaced with the updated value.
> fix: Ensure delete followed by create with same ID works

- internal/session/command.go
We can now inspect the full message on append.
> fix: Log IMAP literals with append

- connector/dummy_simulate.go
- imap/update_message_updated.go
- internal/backend/connector_updates.go
- internal/backend/user.go
- tests/deleted_test.go
- tests/session_test.go
To be used in cases where one needs to atomically replace a message (e.g: Drafts) in one go. This was previously possible with a combination of Delete + Create update, but these were not guaranteed to be atomic and could cause undefined behaviors if something else happened in between.
The old logic to handle the replacement of delete messages on create has been reverted. It is now expected that this type of behavior uses the newly introduced update.
> feat: MessageUpdated Update

- internal/parser/grammar/RFC2047Lexer.g4
- internal/parser/grammar/RFC2047Parser.g4
- internal/parser/src/rfc2047/rfc2047_parser.cpp
- internal/parser/tests/parser/address_list_test.cpp
Rewrite grammar so that it correctly handles the case where the encode text starts with '='.
> fix(GODT-2032): AddressList parsing with encoded text that starts with =

- internal/backend/connector_updates.go
- internal/backend/state_user_interface_impl.go
- internal/backend/user.go
- internal/db/mailbox.go
- internal/db/message.go
- internal/ids/ids.go
- internal/state/actions.go
- internal/state/mailbox.go
- internal/state/state.go
- internal/state/user_interface.go
- tests/counts_test.go
- tests/recovery_mailbox_test.go
- tests/updates_test.go
Add a Gluon managed mailbox which stores messages which failed to be appended. This is required to handle clients such as Outlook which do not check Append failures when moving message and can result in data loss.
When an Append fails, we insert it into a special mailbox called "RecoveredMessages". Messages in this mailbox support:
* Being copied out
* Being moved out
* Flag modifications
* Being deleted
Any other operation is not allowed.
When messages are moved/copied out of this mailbox they are first created as new messages on the Connector before being added to the target mailbox.
> feat(GODT-1989): Recovery Mailbox

- .github/workflows/pull-request.yml
- internal/db/mailbox.go
- internal/state/actions.go
- internal/state/mailbox.go
- rfc822/header.go
- rfc822/header_test.go
- tests/draft_test.go
When adding a message to a mailbox, it can happen that the message is already there. In that case, we remove it and re-add it. However, that change only needs to be done locally; it's useless to do it on the remote. Further, it can even be dangerous to do on the remote, as the remote might handle this as a permanent deletion.
> fix: RemoveMessagesFromMailbox should only remove from remote if need be

- internal/state/responders.go
Always return the total number of messages in the exists unilateral update. We were previous returning the SeqID of the inserted message, but this was not guaranteed to be the last message in the mailbox when the updated arrived from other sessions.
> fix(GODT-1967): Fix Seq ID too high

- internal/parser/grammar/RFC5322AddressListLexer.g4
- internal/parser/tests/parser/address_list_test.cpp
Some of the tokens were being reported to the parser which was breaking the parsing rules.
> fix(GODT-2185): Fix mail address parsing with & in name

- builder.go
- internal/backend/backend.go
- internal/backend/connector_updates.go
- internal/backend/user.go
- internal/db/mailbox.go
- internal/session/session.go
- internal/state/actions.go
- internal/state/mailbox.go
- internal/state/state.go
- internal/state/updates_mailbox.go
- limits/imap.go
- option.go
- tests/imap_limits_test.go
- tests/server_test.go
Add limit checks for mailbox count, messages per mailbox, UID and UIDValidity so that we don't run into issues related exceeding the maximum representable size for each of these data types (uint32).
> feat(GODT-1970): Soft limits

- internal/response/list.go
- internal/session/handle_list.go
- internal/session/handle_lsub.go
- internal/session/handle_status.go
- tests/list_test.go
- tests/lsub_test.go
- tests/status_test.go
Some responses which contain mailbox names were not encoded into utf7. This can lead to duplicate subscription folders and IMAP clients being unable to list the contents of a mailbox.
> fix(GODT-2207): Fix missing utf7 encoding for responses

- connector/dummy.go
- connector/dummy_simulate.go
- imap/update_message_created.go
- internal/backend/connector_updates.go
- tests/session_test.go
- tests/updates_test.go
When setting IgnoreUnknownMailboxIDs is set to true the update will no longer fail and will instead try to create the message and insert it to only mailboxes Gluon is aware off.
This can be useful during an synchronization with connector state a startup.
> feat: Allow MessageCreateUpdate ignore missing mailbox IDs

- imap/structure_test.go
- rfc822/mime.go
- rfc822/parser.go
If we run into an invalid mime type do not block parsing and upload of the message. When this happen we simply report nothing as MIME type. This works as we only use this information internally to reply to FETCH BODY and BODYSTRUCTURE requests.
Finally we also ensure that the Content-Type value only contains valid ASCII characters before being processed.
> fix(GODT-2188): Do not fail APPEND  with invalid MIME types

- benchmarks/gluon_bench/imap_benchmarks/append.go
- internal/state/snapshot.go
- internal/state/snapshot_messages.go
- internal/state/snapshot_messages_test.go
Ensure that sequence set intervals with request interval "N:*" in a mailbox with N-1 messages behaves correctly.
Refactor some of the Snapshot to make it easier to test.
> fix(GODT-2218): Fix invalid UID/Seq ID Sequence range

- connector/connector.go
- connector/dummy.go
- internal/backend/state_connector_impl.go
- internal/state/actions.go
- internal/state/connector.go
- internal/state/updates_mailbox.go
- tests/move_test.go
- tests/recovery_mailbox_test.go
Update connector interface to signal Gluon whether to expunge the original messages after a move command. This is required so that we can correctly support the concept of mail labels.
> feat(GODT-1817): Extend move to not expunge original messages

- internal/state/actions.go
- internal/state/mailbox.go
- tests/append_test.go
When receiving the same remote message ID or appending a message with a known internal ID, we should remote the delete flag from the original original message when it gets moved. This was working in Gluon but never tested for. This patch contains 2 tests that verify this behavior.
> Test: Check for delete falg removal on duplication

- internal/state/responders.go
- internal/state/snapshot.go
- internal/state/snapshot_messages.go
- internal/state/snapshot_messages_test.go
Gracefully handle the rare case that an out of order UID insertion can occur. Make a report in the two possible cases where this could take place.
> fix: Do not crash on out of order UID

- connector/dummy.go
- connector/dummy_test.go
- imap/update_waiter.go
- internal/backend/connector_updates.go
- internal/backend/update_injector.go
- tests/imap_limits_test.go
- tests/recent_test.go
- tests/session_test.go
- tests/updates_test.go
When applying updates from the connector report the error, if any, via the channel the connector is using to wait for the update to complete its execution.
Extend the dummy connector with an option to allow updates to fail as it is impossible to avoid these under certain circumstances.
> fix(GODT-2202): Report update errors to connector

- internal/state/state.go
- tests/cache_reset_test.go
Gluon's internal ID header was not being applied to messages which are re-downloaded from the connector if they are not available in the local cache.
> fix(GODT-2311): Add missing header to downloaded message.

- events/login_failed.go
- internal/session/handle_login.go
- tests/login_test.go
Whenever an IMAP login fails, a `LoginFailed` event will be published.
> feat(GODT-2295): publish event when IMAP login fails.

- store/disk.go
We don't need to pay the extra cost of directory clean up when we are only dealing with full file paths.
> fix: Use os.Remove instead of os.RemoveAll for store files

- connector/connector.go
- connector/dummy.go
- imap/mailbox.go
- internal/backend/state_connector_impl.go
- internal/state/connector.go
- internal/state/state.go
- tests/list_test.go
- tests/lsub_test.go
- tests/session_test.go
The Connector 
`IsMailboxVisible(ctx context.Context, mboxID imap.MailboxID) bool`
has been changed to 
`GetMailboxVisibility(ctx context.Context, mboxID imap.MailboxID) imap.MailboxVisibility`
to allow to specify that a mailbox is to be hidden if empty.
> feat(GODT-1264): adds 'Hidden if empty' options for mailboxes.

- imap/command/append.go
- imap/command/append_test.go
- imap/command/command.go
- imap/command/date_time.go
- imap/command/date_time_test.go
- imap/command/list.go
- imap/command/list_test.go
- imap/command/parser.go
- imap/command/parser_test.go
- imap/parser/parser.go
- imap/parser/parser_test.go
- imap/parser/scanner.go
Lay the foundations for native parsers in Go so we can move away from the C++ libraries.
This patch sets up the foundations to convert the remaining commands to this new format. At the moment the List and Append command have been ported and should serve as an example for the remaining commands.
More commands will follow in future patches.
> feat(GODT-2201): Native GO IMAP Parser Foundations

- imap/command/capability.go
- imap/command/capability_test.go
- imap/command/check.go
- imap/command/check_test.go
- imap/command/close.go
- imap/command/close_test.go
- imap/command/done.go
- imap/command/done_test.go
- imap/command/expunge.go
- imap/command/expunge_test.go
- imap/command/idle.go
- imap/command/idle_test.go
- imap/command/logout.go
- imap/command/logout_test.go
- imap/command/noop.go
- imap/command/noop_test.go
- imap/command/parser.go
- imap/command/starttls.go
- imap/command/starttls_test.go
- imap/command/unselect.go
- imap/command/unselect_test.go
Implements the following IMAP commands which have no attached values:
* Capability
* Check
* Close
* Done
* Expunge
* Idle
* Logout
* Noop
* Unselect
> feat(GODT-2201): IMAP Empty Value Commands

- internal/backend/connector_updates.go
- internal/db/message.go
- tests/updates_test.go
Ensure that when a message gets update, we defer deletion of the message so that it remains accessible until all snapshots that have this message have been released.
> fix(GODT-2399): Defer updated message deletion

- internal/ids/ids.go
- internal/state/actions.go
- internal/state/state.go
They don't exist on the connector.
> fix(GODT-2417): Do no attempt to re-download recovered messages

- connector/connector.go
- internal/session/errors.go
- internal/session/handle_append.go
- internal/session/handle_copy.go
- internal/session/handle_create.go
- internal/session/handle_delete.go
- internal/session/handle_fetch.go
- internal/session/handle_move.go
- internal/session/handle_store.go
Introduce the `ErrOperationNotAllowed` and add the `shouldReportIMAPCommandError` to check whether the failure should be reported. The latter will check whether the error should be reported.
> fix: Reduce reporter noise

- internal/response/item_uid.go
- internal/state/updates.go
When adding or removing flags, we should only notify the messages that have been modified in the process.
> fix(2425): Ensure message flag updates are only issued if changed

- builder.go
- internal/db/db.go
Unfortunately, closing the Ent database clients doesn't guarantee that all the SQLite db files are closed. This causes issues on Windows where the files are locked, making it impossible to remove and re-add the same user.
> fix(GODT-2442): Use rename instead of remove for db files

- internal/state/state.go
- tests/rename_test.go
When renaming a mailbox with inferiors, do not issue rename requests to the connector for the inferiors. The connector should internally handle this. We should only rename the mailboxes locally to avoid waiting on the connector event.
> fix(GODT-2418): Do not issue connector renames for inferiors

- imap/command/input_collector.go
Only copy the number of bytes read instead of the whole buffer.
> fix: InputCollector byte copy range

- imap/structure_test.go
- rfc822/scanner.go
Fix a crash that can occur when scanning for '\n' after '\r' and we reached the end of the input.
> fix(GODT-2513): Fix crash in scanner

- rfc822/header.go
- rfc822/header_parser.go
- rfc822/header_test.go
- tests/fetch_body_test.go
- tests/fetch_test.go
The handling of Preludes in the headers stem from the MBox format. According to the IMAP spec, the literal submitted to APPEND should be a valid RFC822 formatted message.
The handling of the prelude was also causing issues where an MBox formatted entry would slip through and then cause issues later.
> fix(GODT-2573): Remove Prelude header parsing support

- internal/utils/message_hashmap.go
- rfc822/hash.go
- tests/recovery_mailbox_test.go
- tests/testdata/multipart-mixed2.eml
Improve the message hashing by ensuring we hash the body of each part of the message rather than just the entire blob. This will ensure we can handle cases where the only thing that changes between messages is the part identifiers.
> fix(GODT-2582): Improve message hashing for recovery dedup

- imap/structure_test.go
- rfc5322/parser_test.go
- rfc822/parser_test.go
Adding [Go Fuzzing](https://go.dev/security/fuzz/) support to identify bugs.
These files can be used in Go-lang [OSS-Fuzz](https://google.github.io/oss-fuzz/getting-started/new-project-guide/go-lang/) integration.
Edit:
Bug found by PR:  https://github.com/ProtonMail/gluon/commit/8ec759b512f149ed6fd34428cfb5f0fd0fa94e8a https://github.com/ProtonMail/gluon/commit/dfde413d521f01b00bcd9c03038b7f82b7aaf16d
> [Fuzzing] OSS-Fuzz Support for Fuzzing

- async/group.go
Always defer wait group done on the goroutine to avoid stalls in case of panics.
> fix: Defer wg.Done() in Group.Once() 

- internal/backend/connector_updates.go
- tests/updates_test.go
When a mailbox is deleted from the connector, make sure it is also removed from the subscription list.
> fix(GODT-2619): Ensure mailbox deletions from connector unsubscribe

- internal/state/actions.go
- internal/state/mailbox.go
- internal/state/mailbox_fetch.go
- internal/state/mailbox_search.go
- internal/state/state.go
- internal/state/updates.go
- internal/state/updates_remote.go
Ensure that all changes to the DB are made before publishing state updates for connected sessions. This improves stability of the connected clients.
The states still require another transaction to be applied. However, this is currently only related to the handling of the recent flag. This will be handled in GODT-2522 instead.
> fix(GODT-2454): Only apply state updates if db transactions succeed

- internal/backend/connector_updates.go
- store/write_controlled_store.go
Cleanup cache files we generate when creating messages from the connector if the db transaction was not committed successfully.
> fix(GODT-2649): Clean up cache files if connector create message fails

- benchmarks/gluon_bench/imap_benchmarks/select_fetch.go
- benchmarks/gluon_bench/utils/messages.go
- db/ops_mailbox.go
- db/ops_message.go
- db/types.go
- internal/backend/connector_updates.go
- internal/db_impl/sqlite3/migration_test.go
- internal/db_impl/sqlite3/read_ops.go
- internal/db_impl/sqlite3/types.go
- internal/db_impl/sqlite3/utils/tracer.go
- internal/db_impl/sqlite3/write_ops.go
- internal/state/actions.go
- internal/state/match.go
- internal/state/state.go
* Add select-fetch benchmark
* Cleanup old db types
> Refactor GODT-2522

- internal/db_impl/sqlite3/migration_test.go
- internal/db_impl/sqlite3/v1/mailbox.go
- internal/db_impl/sqlite3/v1/migration.go
The first db schema could end up with unresolved references that were never corrected. These can cause migration to fail. Adjust migration code to ignore these.
> fix(GODT-2522): Handle invalid message flag migration

- internal/backend/connector_updates.go
If there are no changes to the literal, besides applying mailbox changes we also need to apply flag changes.
> fix(GODT-2578): Apply flag changes on message update event

- internal/backend/connector_updates.go
Ensure that state updates are only applied after the database transaction has completed.
> fix(GODT-2755): Only apply state updates after transaction commit

- .github/workflows/pull-request.yml
- internal/state/updates.go
- tests/store_test.go
Check that the flagset is not empty before proceeding with the database modifications.
> fix(GODT-2758): Fix panic in SetFlagsOnMessages
