.github/workflows/release.yml
This rule is always triggering regardless of whether the files have been
changed or not.
=> chore: Attempt to fix build parser rules

tests/store_test.go
Add a test which checks whether the \Deleted and \Recent message flags
are persisted between server runs.
=> test(GODT-1649): Add test to check if message flags are persisted

internal/backend/mailbox_tx.go, internal/backend/message_tx.go, internal/backend/snapshot.go, tests/benchmark_big_mailbox_test.go, tests/session_test.go
Fixes too many sql errors on snapshot setup.
Separate patch to reduce the amount of data retrieved from the database.
=> GODT-1615 Fix too many sql errors 

tests/multi_test.go
This adds a test that we match the behavior of dovecot regarding operations on expunged messages.
=> test: Add test for setting flags on expunged message

benchmarks/README.md, benchmarks/imaptest/README.md, benchmarks/imaptest/default.sh, benchmarks/imaptest/full.sh, demo/demo.go, go.mod, go.sum
- Setup Demo project to produce profiling output.
- Provide ImapTest scripts
- Add documentation on how to use imap test and profile data.
=> ImapTest tool integration and demo profiling setup

benchmarks/gluon_bench/benchmarks/copy.go, benchmarks/gluon_bench/benchmarks/fetch.go, benchmarks/gluon_bench/flags/general.go, benchmarks/gluon_bench/main.go, benchmarks/gluon_bench/server/local.go, benchmarks/gluon_bench/utils/utils.go
Adds a copy benchmark with similar options as the fetch benchmark as well as some minor cleanup.
=> Add copy benchmark

benchmarks/gluon_bench/benchmarks/expunge.go, benchmarks/gluon_bench/benchmarks/search.go, benchmarks/gluon_bench/main.go, benchmarks/gluon_bench/utils/utils.go
Adds search benchmarks for TEXT and SINCE queries. Data can be generated
randomly or fed via a new line separated text file.
=> Search benchmark

internal/backend/mailbox_fetch.go, internal/backend/mailbox_search.go, internal/backend/seqset.go, internal/backend/snapshot.go, internal/backend/state_actions.go, internal/backend/state_updates.go, internal/backend/user_state.go, internal/backend/user_updates.go
Converted most panics that can be handled properly as an error to error.
=> fix(GODT-1749): Convert panics to errors

internal/state/filters.go, internal/state/responders.go, internal/state/updates.go, tests/move_test.go
Improve state update log info.
Add flushes to TestMoveBackAndForth.
=> Minor chores

builder.go, internal/backend/backend.go, internal/backend/connector_updates.go, internal/backend/user.go, internal/db/db.go, internal/session/command.go, internal/session/handle_append.go, internal/session/handle_copy.go, internal/session/handle_create.go, internal/session/handle_delete.go, internal/session/handle_fetch.go, internal/session/handle_move.go, internal/session/handle_store.go, internal/state/actions.go, internal/state/mailbox.go, internal/state/state.go, option.go, reporter/context.go, reporter/null_reporter.go, reporter/reporter.go, reporter/utils.go, server.go, store/store.go
Add support for remote reporting and report some information of interest.
=> GODT-1773 reporter integration

internal/db/message.go, internal/state/actions.go
Reduces the total amount of database queries for Append by having an optimized path that re-use previously available calculations.
=> refactor(GODT-1570): Add CreateAndAddMessageToMailbox

connector/dummy_simulate.go, internal/backend/connector_updates.go, tests/session_test.go, tests/updates_test.go
Fix connector updates for create message. There was a bug in them related to messages with the same ID.
=> fix: ConnectorUpdate CreateMessage

internal/db/mailbox.go, internal/state/snapshot.go, internal/state/snapshot_messages.go, internal/state/snapshot_messages_test.go
=> Refactor snapshot db query 

internal/backend/connector_updates.go, internal/db/mailbox.go, internal/db/message.go, internal/state/actions.go, internal/state/mailbox.go, internal/state/updates_mailbox.go, tests/copy_test.go
The following collection of changes improves COPY perf by 9-10x.
=> Improve Performance of COPY command

connector/dummy.go, imap/flags.go, internal/backend/connector_updates.go, internal/backend/state_connector_impl.go, internal/db/message.go, internal/session/handle_examine.go, internal/session/handle_select.go, internal/session/handle_status.go, internal/state/actions.go, internal/state/mailbox.go, internal/state/mailbox_fetch.go, internal/state/mailbox_search.go, internal/state/responders.go, internal/state/snapshot.go, internal/state/snapshot_messages.go, internal/state/updates.go
Avoid scanning all the messages if we only need one message or a number of messages.
=> refactor(GODT-1570): Improve Examine, Status and Select + Batch flag processing

internal/parser/grammar/CMakeLists.txt, internal/parser/src/parser.cpp, internal/parser/src/visitor.cpp, internal/parser/vcpkg.json
This patch also fixes the version in vcpkg.
=> chore: Update ANLTR to v4.10.1

queue/queued_channel.go, queue/queued_channel_test.go
Force exists the goroutine that populates the channel.
=> fix: Add QueuedChannel.CloseAndDiscardQueued

internal/backend/update_injector.go, internal/backend/user.go, internal/session/command.go, internal/session/handle.go, internal/session/handle_idle.go, logging/flags_debug.go, logging/flags_default.go, logging/logging.go, logging/pprof_default.go, logging/pprof_disabled.go, queue/queued_channel.go, server.go, tests/full_state_test.go, tests/server_test.go
This change adds a logging package which makes it easy to annotate goroutines with labels that appear in pprof profiles.
Existing annotations were converted to use the new package.
=> feat: Improve goroutine annotation

.github/workflows/parser-build-and-push.yml, .github/workflows/pull-request.yml, internal/parser/CMakeLists.txt
Add small comment to force rebuild the parser libs.
=> fix: Ensure Linux builds are using 20.04 image

internal/backend/connector_updates.go, tests/deleted_test.go
Make sure that if there are no literal changes, we still assign the message to the mailboxes it has listed.
=> fix(GODT-2226): Reassign message to mailbox on MessageUpdate

internal/state/mailbox_fetch.go
When fetching messages with the keywords RFC822, RFC822Header and RFC822Text we were retrieving the literal from the store again rather than using the cached version as originally intended.
=> fix: Use previously cached literal in fetch keywords

imap/command/parser.go, imap/command/uid.go, imap/command/uid_test.go
Includes the default UID commands and UID Expunge.
=> feat(GODT-2201): IMAP UID Commands

imap/command/input_collector.go, imap/command/input_collector_test.go, imap/command/parser.go, imap/command/parser_test.go, rfcparser/parser.go, rfcparser/scanner.go
* Ensure we can skip malformed commands (read until new line)
* Properly handle continuation for literals
* Allow for command input collection to debug later
=> Fixes + Refactor

.github/workflows/pull-request.yml, store/disk.go, store/fallback.go, store/fallback_v0/compressor.go, store/fallback_v0/compressor_gzip.go, store/fallback_v0/compressor_zlib.go, store/fallback_v0/disk.go, store/option.go, store/store_test.go, tests/updates_test.go
* Add header to store files
* Allow fallback reader to read old files.
=> GODT-2385: Store fallback mechanism 

internal/session/handle.go
In the case there is an unexpected issue with the IMAP command, still allow pending state updates to be applied.
=> fix(GODT-2400): Allow state updates to be applied if command fails

.github/workflows/pull-request.yml, benchmarks/imaptest/main_test.go, store/store_test.go, tests/close_test.go, tests/multi_test.go
Attempt to fix some flaky tests by adding more flushes.
Fix linter issues for v1.51.1.
=> chore: Flaky tests + linter

rfc822/header_parser.go, rfc822/header_test.go
Ensure the header parser treats the sequence `\r\n ` as a fold in accordance to RFC5322. The original tests for the header parser did not adhere to this convention and led to the incorrect parser logic.
=> fix(GODT-2427): Fix header parsing logic

internal/db/db.go, internal/session/errors.go, internal/state/errors.go, internal/state/mailbox.go, internal/state/state.go, internal/utils/utils.go
Reduces report spam caused by known errors during IMAP commands.
=> fix(GODT-2419): Reduce sentry reporter spam

internal/db/db.go, tests/account_test.go, tests/server_test.go, tests/session_test.go
The glob pattern '*' was missing from the file path. Add unit test to catch issue in the future.
=> fix(GODT-2442): Fix problem introduce in code review

internal/session/handle.go, internal/session/session.go
This bug was introduced when we switch for a queued channel to handle the client's responses. This had the unfortunate side effect that if the responses would arrive faster than they can be sent to client they can pile up. When this is combined with fetch queries that read the message literal, an unhealthy amount of RAM can be consumed by this.
=> fix(GODT-2526): Unlimited memory usage during fetch/search

imap/capabilities.go, internal/session/handle_capability.go, internal/session/session.go, tests/capability_test.go, tests/login_test.go
Feature was built in but never announced to the clients.
=> fix(GODT-2550): Announce IMAP ID Capability

connector/dummy.go, connector/dummy_simulate.go, connector/dummy_state.go, imap/flags.go, imap/update_message_flags_updated.go, imap/update_message_labels_updated.go, internal/backend/connector_updates.go, tests/state_test.go
Allow connector to specify any combination of flags that it requires rather than a fixed list.
=> refactor(GODT-2576): Allow any type of flag to be set in updates

internal/backend/backend.go, internal/backend/user.go, internal/db_impl/db_impl.go, internal/db_impl/sqlite3/client.go, internal/db_impl/sqlite3/v1/migration.go, tests/migration_test.go
When migration fails auto-recreate the database.
=> feat(GODT-2522): migration recovery

internal/session/context.go, rfc5322/validation.go, rfc5322/validation_test.go
See commit details for more info.
=> fix GODT-2757 & GODT-2776
